import { Inter } from "next/font/google";
import "./globals.css";
import Nav from "@/components/Nav";
import Provider from "@/components/providers";
import { Toaster } from "@/components/ui/toaster";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="bg-gradient-to-t from-green-200 to-green-100">
      <Provider>
        <body className={inter.className}>
          <Nav></Nav>
          {children}
          <Toaster/>
        </body>
      </Provider>
    </html>
  );
}
